# Generated by Django 4.0.2 on 2022-04-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='login',
            name='type',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
