# Generated by Django 4.0.4 on 2022-05-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userreg_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
