# Generated by Django 4.0.4 on 2022-05-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_bookings_pid_bookings_rate_bookings_wname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='feedback',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
