# Generated by Django 4.0.4 on 2022-05-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_bookings_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
