# Generated by Django 4.0.4 on 2022-05-15 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_bookings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='wname',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='wphone',
        ),
    ]
