# Generated by Django 4.0.2 on 2022-04-04 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_login_status_login_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerreg',
            fields=[
                ('sid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.login')),
                ('sname', models.CharField(max_length=50)),
                ('oname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('license', models.CharField(max_length=60)),
            ],
        ),
    ]
