# Generated by Django 4.0.2 on 2022-04-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerreg',
            old_name='sid',
            new_name='pid',
        ),
    ]
