# Generated by Django 4.0.4 on 2022-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_rename_sid_partnerreg_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('wname', models.CharField(max_length=60)),
                ('wphone', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='partneroffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('wname', models.CharField(max_length=60)),
                ('wphone', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
