# Generated by Django 4.0.4 on 2022-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_delete_order_delete_partneroffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('details', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('wname', models.CharField(max_length=60)),
                ('wphone', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('finalamt', models.IntegerField()),
                ('feedback', models.CharField(max_length=350)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='partneroffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('wname', models.CharField(max_length=60)),
                ('wphone', models.IntegerField()),
                ('rate', models.IntegerField()),
            ],
        ),
    ]
